version: '3'
services:
  zinc-search:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - '4080:4080'
    networks:
      - main_network
  service:
    build:
      context: ./service
      dockerfile: ./Dockerfile
      args:
        progress: plain
    environment:
      - ZINCSEARCH_HOST=http://zinc-search:4080
      - ZINCSEARCH_USERNAME=${ZINC_FIRST_ADMIN_USER}
      - ZINCSEARCH_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      - zinc-search
    networks:
      - main_network
    restart: on-failure
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        progress: plain
        SERVICE_HOST: http://service:3000
    ports:
      - 8080:8080
    depends_on:
      - service
    networks:
      - main_network
    restart: on-failure

networks:
  main_network:
    driver: bridge
